### ISSUE TITLE
[question] Saving changes to the rom file

### ISSUE THREAD

**Issue by cIymax** [sporst/Daybreak#2]
Hi Sebastian,

First of all, thank you for creating and sharing your Daybreak map editor for Faxanadu for the NES.

1. I was able to get the map editor running and was able to make changes.  But I couldn't find how to save my changes to the rom file.

2. The NES Hacking Framework (NHF), which the editor relies on, contains write methods in certain files (namely, FileHelpers.java and INesSplitter.java).  But it's unclear that these methods are called by the map editor.  I also looked at your blog but found no answers.

3. Was it perhaps an unfinished feature of the map editor?  If so, I wonder how close the map editor is to having that feature, in terms of the development effort needed.

Any insight would be greatly appreciated.  Thank you.

**Comment by sporst** [comment]
Hey there, no idea I'm afraid. I worked on Daybreak about 15 years ago and haven't looked at it since. It's incomplete though. I remember in particular how I had trouble writing level data back after door locations/destinations changed. I don't think I've ever implemented that.

**Comment by cIymax** [comment]
Thanks for the quick confirmation!  No worries, and great work so far by the way.  I'll mark this question as closed.
